//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinMillionsServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public Block()
        {
            this.TransactionDetail = new HashSet<TransactionDetail>();
        }
    
        public int ID { get; set; }
        public string Hash { get; set; }
        public int Confirmations { get; set; }
        public int Height { get; set; }
        public int Version { get; set; }
        public string MerkleRoot { get; set; }
        public int Time { get; set; }
        public string Nonce { get; set; }
        public string Bits { get; set; }
        public float Difficulty { get; set; }
        public string PreviousBlockHash { get; set; }
        public string NextBlockHash { get; set; }
    
        public virtual ICollection<TransactionDetail> TransactionDetail { get; set; }
    }
}
