//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinMillionsServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawBlock : Block
    {
        public DrawBlock()
        {
            this.TicketTxes = new HashSet<TicketTx>();
        }
    
    
        public virtual Ticket Tickets { get; set; }
        public virtual ICollection<TicketTx> TicketTxes { get; set; }
    }
}
